INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'foundZusatznamenkommentar', 'Für Belegform %s wurde Zusatznamenkommentar %s gefunden. NamenkommentarID: %s, EinzelbelegIDs: %s', 'For form of reference %s, additional name comment %s was found. Commentary(name)ID %s, Single referenceIDs: %s', 'Pour la forme de référence %s, un commentaire sur le nom supplémentaire %s a été trouvé. ID du commentaire %s, références individuelles IDs : %s', 'Pro forma testimonii %s, commentarium additicius nominis %s repertum est. ID commentarii %s, testimonium individuorum IDs: %s');


INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'replaceZusatznamenkommentar', 'Soll dieser Zusatznamenkommentar hier übernommen werden?', 'Should this additional name comment be adopted here?', 'Ce commentaire sur le nom supplémentaire doit-il être adopté ici ?', 'Debetne hoc commentarium nominis additicius hic assumptum?');

INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'cleanData', 'Bitte bereinigen Sie die Daten!', 'Please clean up the data!', 'Veuillez nettoyer les données !', 'Quaeso data purganda sunt!');

INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'foundLemma', 'Für Belegform %s wurde das Lemma %s gefunden. LemmaID: %s, EinzelbelegIDs: %s', 'For form of reference %s, Lemma %s was found. LemmaID %s, Single referenceIDs: %s', 'Pour la forme de référence %s, le lemme %s a été trouvé. ID du lemme %s, références individuelles IDs : %s\"', 'Pro forma testimonii %s, lemma %s repertum est. ID lemma %s, testimonium individuorum IDs: %s');

INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'replaceLemma', 'Soll dieser Lemma hier übernommen werden?', 'Should this lemma be adopted here?', 'Ce lemme doit-il être adopté ici ?', 'Debetne hoc lemma hic assumptum?');

INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('funktionen', 'deleteEntry', 'Soll dieser Eintrag wirklich gelöscht werden? Alle bisherigen Änderungen in diesem Formular werden verworfen!', 'Should this entry really be deleted? All previous changes in this form will be discarded!', 'Cette entrée doit-elle vraiment être supprimée ? Toutes les modifications précédentes apportées à ce formulaire seront ignorées !', 'Num hic ingressus vere delebitur? Omnes priores mutationes in hoc formulario reicientur!');
