UPDATE `datenbank_mapping` SET `gb_beschriftung` = 'Dating of the Reference', `fr_beschriftung` = 'Datation de la référence', `la_beschriftung` = 'Testimonii definitio temporis' where Formular = "gast_einzelbeleg" and Datenfeld = "Datierung";

UPDATE `datenbank_mapping` SET `de_Beschriftung` = ' Kurztitel', `gb_beschriftung` = ' Short-title', `fr_beschriftung` = 'Abrévation du titre', `la_beschriftung` = 'Inscriptio abbreviata' where Formular = "einzelbeleg" and Datenfeld = "QuelleLink";

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `ZielTabelle`, `ZielAttribut`, `Seite`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('gast_einzelbeleg', 'Edition', 'Edition', 'sqlselect', '0', 'einzelbeleg', 'EditionID', 'einzelbeleg', 'Edition', 'Édition', 'Editio');

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `ZielTabelle`, `ZielAttribut`, `Seite`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('gast_einzelbeleg', 'EditionKapitel', 'Kapitel', 'textfield', '0', 'einzelbeleg', 'EditionKapitel', 'einzelbeleg', 'Chapter', 'Chapitre', 'Capitulum');

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `ZielTabelle`, `ZielAttribut`, `Seite`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('gast_einzelbeleg', 'EditionSeite', 'Seite', 'textfield', '0', 'einzelbeleg', 'EditionSeite', 'einzelbeleg', 'Page', 'Page', 'Pagina');

UPDATE `datenbank_mapping` SET `de_Beschriftung` = 'Person', `gb_beschriftung` = 'Person', `fr_beschriftung` = 'Personne', `la_beschriftung` = 'Persona' WHERE Formular = "person" and Datenfeld = "Standardname";

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `ZielTabelle`, `ZielAttribut`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('gast_person', 'Identifizierungsproblem', 'Kommentar', 'textarea', '0', 'person', 'Identifizierungsproblem', 'Comment', 'Commentaire', 'Commentarius');

UPDATE `datenbank_mapping` SET `de_Beschriftung` = 'Ämter', `gb_beschriftung` = 'Offices', `fr_beschriftung` = 'Fonctions', `la_beschriftung` = 'Officia' WHERE Formular = "person" and Datenfeld = "AmtWeihe";

UPDATE `datenbank_mapping` SET `gb_beschriftung` = 'Dating', `fr_beschriftung` = 'Datation', `la_beschriftung` = 'Definitio temporis' WHERE Formular = "gast_quelle" and Datenfeld = "Datierung";

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('gast_quelle', 'WeitereEditionen', 'Weitere Editionen', 'textfield', '0', 'Further Editions', 'Éditions supplémentaires', 'Editiones alterae');

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('freie_suche', 'ErstZweitGlied', 'Erst-/ Zweitglied', 'select', '0', 'First/ Second part', 'Première/ Deuxième partie', 'Prima/ Secunda pars');

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('freie_suche', 'Sortierung1', 'Gruppieren nach', 'textfield', '0', 'sort according to', 'trier par', 'primo in genera digerere');

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('freie_suche', 'Sortierung2', 'Anschließend nach', 'textfield', '0', 'afterwards according to', 'ensuite par', 'deinde');

INSERT INTO `datenbank_mapping` (`Formular`, `Datenfeld`, `de_Beschriftung`, `Feldtyp`, `Array`, `gb_beschriftung`, `fr_beschriftung`, `la_beschriftung`) VALUES ('freie_suche', 'Sortierung3', 'Dann nach', 'textfield', '0', 'finally according to', 'finalement par', 'postremo');

INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('startseite', 'Datenschutzerklaerung', 'Datenschutzerklärung', 'Privacy Policy', 'Politique de confidentialité', 'Declaratio secreti');

UPDATE `datenbank_mapping` SET `de_Beschriftung` = 'ID', `gb_beschriftung` = 'ID', `fr_beschriftung` = 'ID', `la_beschriftung` = 'ID' WHERE Formular = "freie_suche" and Datenfeld = "NeGID";

UPDATE `datenbank_mapping` SET `de_Beschriftung` = 'Person', `gb_beschriftung` = 'Person', `fr_beschriftung` = 'Personne', `la_beschriftung` = 'Persona' WHERE Formular = "freie_suche" and Datenfeld = "Personenname";

UPDATE `datenbank_mapping` SET `de_Beschriftung` = 'lebend / verstorben', `gb_beschriftung` = 'alive/dead', `la_beschriftung` = 'vivus/mortuus' WHERE Formular = "freie_suche" and Datenfeld = "Ausgabe_Einzelbeleg_lebend";

UPDATE `datenbank_mapping` SET `de_Tooltip` = 'Die ID besteht aus einem Buchstaben für die Art des Datensatzes (B=Einzelbeleg, E=Edition, M=MGH-Lemma, N=NamenLemma, P=Person, Q=Quelle) + laufender Nummer (z. b. P 7404 = Karl der Große). Geben Sie hier eine vollständige ID ein. Die ID finden Sie oben rechts in jedem Datensatz-Eintrag', `gb_Tooltip` = 'The ID consists of a letter (B = single reference, P = Person, Q = Source) + a specific number (e.g. P 7404 = Charlemagne). Please enter a complete ID in this field. It can be found in the upper right hand corner of every data set entry.', `fr_Tooltip` = 'The ID consists of a letter (B = single reference, P = Person, Q = Source) + a specific number (e.g. P 7404 = Charlemagne). Please enter a complete ID in this field. It can be found in the upper right hand corner of every data set entry.', `la_Tooltip` = 'The ID consists of a letter (B = single reference, P = Person, Q = Source) + a specific number (e.g. P 7404 = Charlemagne). Please enter a complete ID in this field. It can be found in the upper right hand corner of every data set entry.' WHERE Formular = "freie_suche" and Datenfeld = "NeGID";

UPDATE `datenbank_mapping` SET `gb_Tooltip` = 'The form of reference is the explicit mentioning of a name in a source; usually it is inflected and deviates from the modern way of spelling (e.g. Hlodowicus for Louis).', `fr_Tooltip` = 'The form of reference is the explicit mentioning of a name in a source; usually it is inflected and deviates from the modern way of spelling (e.g. Hlodowicus for Louis).', `la_Tooltip` = 'The form of reference is the explicit mentioning of a name in a source; usually it is inflected and deviates from the modern way of spelling (e.g. Hlodowicus for Louis).' WHERE Formular = "freie_suche" and Datenfeld = "Belegform";

UPDATE `datenbank_mapping` SET `de_Platzhalter` = 'Suche nach Personen Namen', `gb_Platzhalter` = 'search for a persons name', `fr_Platzhalter` = 'search for a persons name', `la_Platzhalter` = 'search for a persons name', `gb_Tooltip` = 'The standard names in the database consist of a proper name and further indicator for a definite \r\nidentification in &lt;&gt;: \r\nmodern ordinal numbers, surnames (e.g. &quot;the Great&quot; or anything similar), office or a job description, \r\nand the date of death. Names and other terms in german (Karl d. Gro&szlig;e &lt;Kg. u. Ks.&gt;, + 814 = Charlemagne).', `fr_Tooltip` = 'The standard names in the database consist of a proper name and further indicator for a definite \r\nidentification in &lt;&gt;: \r\nmodern ordinal numbers, surnames (e.g. &quot;the Great&quot; or anything similar), office or a job description, \r\nand the date of death. Names and other terms in german (Karl d. Gro&szlig;e &lt;Kg. u. Ks.&gt;, + 814 = Charlemagne).', `la_Tooltip` = 'The standard names in the database consist of a proper name and further indicator for a definite \r\nidentification in &lt;&gt;: \r\nmodern ordinal numbers, surnames (e.g. &quot;the Great&quot; or anything similar), office or a job description, \r\nand the date of death. Names and other terms in german (Karl d. Gro&szlig;e &lt;Kg. u. Ks.&gt;, + 814 = Charlemagne).' WHERE Formular = "freie_suche" and Datenfeld = "Personenname";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'The different spellings of a name are summarized under a linguistic lemma. In the upper window, select the first part of a lemma, and in the second window, select the second part.', `la_Tooltip` = 'The different spellings of a name are summarized under a linguistic lemma. In the upper window, select the first part of a lemma, and in the second window, select the second part.' WHERE Formular = "freie_suche" and Datenfeld = "ErstGliedSelect";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select the sex from the drop-down menu.', `la_Tooltip` = 'Select the sex from the drop-down menu.' WHERE Formular = "freie_suche" and Datenfeld = "Geschlecht";

UPDATE `datenbank_mapping` SET `fr_Platzhalter` = 'format: 750, 750-799, 8Jh1-8Jh2.', `la_Platzhalter` = 'format: 750, 750-799, 8Jh1-8Jh2.', `fr_Tooltip` = 'Limit the period of the source you want to examine. If you want to focus on the time of origin of a source, \\r\\nyou can do this by using the search column &quot;date of the source&quot;. The following categories \\r\\nare available, use the german abreviation JH (=Jahrhundert) for &quot;century&quot;: \\r\\n&quot;century&quot; (7JH), &quot;first or second half of a century&quot; \\r\\n(&quot;7JH1 or 7JH2&quot;) or exact year dates (&quot;656-686&quot;).', `la_Tooltip` = 'Limit the period of the source you want to examine. If you want to focus on the time of origin of a source, \\r\\nyou can do this by using the search column &quot;date of the source&quot;. The following categories \\r\\nare available, use the german abreviation JH (=Jahrhundert) for &quot;century&quot;: \\r\\n&quot;century&quot; (7JH), &quot;first or second half of a century&quot; \\r\\n(&quot;7JH1 or 7JH2&quot;) or exact year dates (&quot;656-686&quot;).' WHERE Formular = "freie_suche" and Datenfeld = "PersonZeitraum";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select the office from the drop-down menu. This way you can search for certain ministries \\r\\n(Kings, Bishops, Counts,...) or ecclesiastical titles (priest, deacon,...). The entries illustrate the \\r\\ncurrent state of research and may deviate from medieval allocations (see below &quot;ecclesiastical \\r\\noffices/ single reference&quot;).', `la_Tooltip` = 'Select the office from the drop-down menu. This way you can search for certain ministries \\r\\n(Kings, Bishops, Counts,...) or ecclesiastical titles (priest, deacon,...). The entries illustrate the \\r\\ncurrent state of research and may deviate from medieval allocations (see below &quot;ecclesiastical \\r\\noffices/ single reference&quot;).' WHERE Formular = "gast_freie_suche" and Datenfeld = "AmtWeihePerson";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select the status from the drop-down menu.', `la_Tooltip` = 'Select the status from the drop-down menu.' WHERE Formular = "gast_freie_suche" and Datenfeld = "StandPerson";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select the ethnicity from the drop-down menu.', `la_Tooltip` = 'Select the ethnicity from the drop-down menu.' WHERE Formular = "gast_freie_suche" and Datenfeld = "EthniePerson";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select from the drop-down menu. The allocation of an office is medieval and may be wrong seen \\r\\nfrom a modern perspective, e.g. &quot;papa&quot; for early medieval bishops.', `la_Tooltip` = 'Select from the drop-down menu. The allocation of an office is medieval and may be wrong seen \\r\\nfrom a modern perspective, e.g. &quot;papa&quot; for early medieval bishops.' WHERE Formular = "gast_freie_suche" and Datenfeld = "AmtWeiheEinzelbeleg";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select from the drop-down menu', `la_Tooltip` = 'Select from the drop-down menu' WHERE Formular = "gast_freie_suche" and Datenfeld = "EthnieEinzelbeleg";

UPDATE `datenbank_mapping` SET `fr_Tooltip` = 'Select from the drop-down menu', `la_Tooltip` = 'Select from the drop-down menu' WHERE Formular = "gast_freie_suche" and Datenfeld = "Quellenliste";

UPDATE `datenbank_mapping` SET `fr_Platzhalter` = 'e.g. author, title, originator, recipient', `la_Platzhalter` = 'e.g. author, title, originator, recipient', `fr_Tooltip` = 'Format for narrative sources: name of the medieval author, title of the work (&quot;Audoenus of Rouen, \nVita Eligii episcopi Noviomagensis&quot;). Format for charters, all terms in german: dating in four-digit numbers,\n name of the originator, name of the recipient (0687 Pippin d. M. und Plectrud f&uuml;r St. Arnulf in Metz).', `la_Tooltip` = 'Format for narrative sources: name of the medieval author, title of the work (&quot;Audoenus of Rouen, \nVita Eligii episcopi Noviomagensis&quot;). Format for charters, all terms in german: dating in four-digit numbers,\n name of the originator, name of the recipient (0687 Pippin d. M. und Plectrud f&uuml;r St. Arnulf in Metz).' WHERE Formular = "freie_suche" and Datenfeld = "Quelle";

UPDATE `datenbank_mapping` SET `gb_Tooltip` = 'Select from the drop-down menu', `fr_Tooltip` = 'Select from the drop-down menu', `la_Tooltip` = 'Select from the drop-down menu' WHERE Formular = "freie_suche" and Datenfeld = "QuelleGattung";

UPDATE `datenbank_mapping` SET `fr_Platzhalter` = 'format: 750, 750-799, 8Jh1-8Jh2.', `la_Platzhalter` = 'format: 750, 750-799, 8Jh1-8Jh2.', `gb_Tooltip` = 'Narrow down the time period in which the sources originated. Accepted formats: &quot;century&quot; (e.g., &quot;7Jh&quot;), &quot;first or second half of a century&quot; (e.g., &quot;7Jh1&quot; or &quot;7Jh2&quot;), or exact years (e.g., &quot;656–686&quot;). – If you want to limit the reporting period of the source, please use the &quot;Time Frame of Reference (Person)&quot; field above.', `fr_Tooltip` = 'Narrow down the time period in which the sources originated. Accepted formats: &quot;century&quot; (e.g., &quot;7Jh&quot;), &quot;first or second half of a century&quot; (e.g., &quot;7Jh1&quot; or &quot;7Jh2&quot;), or exact years (e.g., &quot;656–686&quot;). – If you want to limit the reporting period of the source, please use the &quot;Time Frame of Reference (Person)&quot; field above.', `la_Tooltip` = 'Narrow down the time period in which the sources originated. Accepted formats: &quot;century&quot; (e.g., &quot;7Jh&quot;), &quot;first or second half of a century&quot; (e.g., &quot;7Jh1&quot; or &quot;7Jh2&quot;), or exact years (e.g., &quot;656–686&quot;). – If you want to limit the reporting period of the source, please use the &quot;Time Frame of Reference (Person)&quot; field above.' WHERE Formular = "freie_suche" and Datenfeld = "QuelleZeitraum";
