INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'IdNotFoundError', 'Einzelbeleg ID B%s ist nicht vorhanden', 'Single Reference ID B%s does not exist', 'L\'ID de référence unique B%s n\'existe pas', 'Identificatio referentialis singularis B%s non exstat');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'NotPublicError', 'Einzelbeleg ID B%s ist nicht zu veröffentlichen', 'Single Reference ID B%s is not to be published', 'L\'ID de référence unique B%s ne doit pas être publié', 'Identificatio referentialis singularis B%s non publicanda est');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('mgh_lemma', 'NotPublicError', 'Lemma ID M%s ist nicht zu veröffentlichen', 'Lemma ID M%s is not to be published', 'L\'ID du lemme M%s ne doit pas être publié', 'Lemma ID M%s non est publicandum');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('mgh_lemma', 'IdNotFoundError', 'Lemma ID M%s ist nicht vorhanden', 'Lemma ID M%s does not exist', 'L\'ID de lemme M%s n\'existe pas', 'Lemma ID M%s non existit');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('mgh_lemma', 'LemmaInvalidString', 'Lemma ID M%s enthält ungültige Zeichenkette -> \'[???]\'', 'Lemma ID M%s contains invalid string -> \'[???]\'', 'L\'ID du lemme M%s contient une chaîne non valide -> \'[???]\'', 'Lemmatis ID M%s seriem litterarum invalidam continet -> \'[???]\'');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('person', 'IdNotFoundError', 'Person ID P%s ist nicht vorhanden', 'Person ID P%s does not exist', 'L\'identifiant de personne P%s n\'existe pas', 'Identificatio personae P%s non exstat');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('person', 'NotPublicError', 'Person ID P%s ist nicht zu veröffentlichen', 'Person ID P%s is not to be published', 'L\'identifiant personnel P%s ne doit pas être publié', 'Identificatio personae P%s non divulganda est');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('quelle', 'IdNotFoundError', 'Quelle ID Q%s ist nicht vorhanden', 'Source ID Q%s does not exist', 'L\'ID source Q%s n\'existe pas', 'Identificatio fontis Q%s non exstat');
INSERT INTO `datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('quelle', 'NotPublicError', 'Quelle ID Q%s ist nicht zu veröffentlichen', 'Source ID Q%s is not to be published', 'L\'ID source Q%s ne doit pas être publié', 'Identificatio fontis Q%s non publicanda est');

